# Generated by Django 3.1.7 on 2021-03-04 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mosh.offices')),
                ('reporst_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_mosh.employees')),
            ],
        ),
    ]
